export const LANG_OPTIONS = [
  { value: "", label: "음성 설정 안함" },
  { value: "nl-NL", label: "네덜란드어" },
  { value: "nb-NO", label: "노르웨이어" },
  { value: "da-DK", label: "덴마크어" },
  { value: "de-DE", label: "독일어" },
  { value: "ru-RU", label: "러시아어" },
  { value: "vi-VN", label: "베트남어" },
  { value: "sv-SE", label: "스웨덴어" },
  { value: "es-ES", label: "스페인어" },
  { value: "ar-SA", label: "아랍어" },
  { value: "en-GB", label: "영어(UK)" },
  { value: "en-US", label: "영어(US)" },
  { value: "it-IT", label: "이탈리아어" },
  { value: "id-ID", label: "인도네시아어" },
  { value: "ja-JP", label: "일본어" },
  { value: "zh-CN", label: "중국어(간체)" },
  { value: "zh-TW", label: "중국어(광둥어/대만)" },
  { value: "zh-HK", label: "중국어(광둥어/홍콩)" },
  { value: "th-TH", label: "태국어" },
  { value: "tr-TR", label: "터키어" },
  { value: "pt-PT", label: "포르투갈어" },
  { value: "pt-BR", label: "포르투갈어(브라질)" },
  { value: "pl-PL", label: "폴란드어" },
  { value: "fr-FR", label: "프랑스어" },
  { value: "fi-FI", label: "핀란드어" },
  { value: "tl-PH", label: "필리핀어" },
  { value: "ko-KR", label: "한국어" },
  { value: "hi-IN", label: "힌디어" },
];

export const DEFAULT_LANG = "en-US";
