export const LANG_OPTIONS = [
  // { value: "", label: "", icon: "" },
  { value: "all", label: "모두다", icon: "🌐" },
  { value: "nl-NL", label: "네덜란드어", icon: "🇳🇱" },
  { value: "nb-NO", label: "노르웨이어", icon: "🇳🇴" },
  { value: "da-DK", label: "덴마크어", icon: "🇩🇰" },
  { value: "de-DE", label: "독일어", icon: "🇩🇪" },
  { value: "ru-RU", label: "러시아어", icon: "🇷🇺" },
  { value: "vi-VN", label: "베트남어", icon: "🇻🇳" },
  { value: "sv-SE", label: "스웨덴어", icon: "🇸🇪" },
  { value: "es-ES", label: "스페인어", icon: "🇪🇸" },
  { value: "ar-SA", label: "아랍어", icon: "🇸🇦" },
  { value: "en-GB", label: "영어(UK)", icon: "🇬🇧" },
  { value: "en-US", label: "영어(US)", icon: "🇺🇸" },
  { value: "it-IT", label: "이탈리아어", icon: "🇮🇹" },
  { value: "id-ID", label: "인도네시아어", icon: "🇮🇩" },
  { value: "ja-JP", label: "일본어", icon: "🇯🇵" },
  { value: "zh-CN", label: "중국어(간체)", icon: "🇨🇳" },
  { value: "zh-TW", label: "중국어(광둥어/대만)", icon: "🇹🇼" },
  { value: "zh-HK", label: "중국어(광둥어/홍콩)", icon: "🇭🇰" },
  { value: "th-TH", label: "태국어", icon: "🇹🇭" },
  { value: "tr-TR", label: "터키어", icon: "🇹🇷" },
  { value: "pt-PT", label: "포르투갈어", icon: "🇵🇹" },
  { value: "pt-BR", label: "포르투갈어(브라질)", icon: "🇧🇷" },
  { value: "pl-PL", label: "폴란드어", icon: "🇵🇱" },
  { value: "fr-FR", label: "프랑스어", icon: "🇫🇷" },
  { value: "fi-FI", label: "핀란드어", icon: "🇫🇮" },
  { value: "tl-PH", label: "필리핀어", icon: "🇵🇭" },
  { value: "ko-KR", label: "한국어", icon: "🇰🇷" },
  { value: "hi-IN", label: "힌디어", icon: "🇮🇳" },
  { value: "etc", label: "기타", icon: "🌐" },
];

export const DEFAULT_LANG = "all";
